name: Release


on:
  push:
    branches: # on push to main
      - main
    paths-ignore:
      - "**/*.json"
    tags: # or tag push (any branch)
      - '*'


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run typecheck
      - run: npm run test
      - run: npm run build
      - name: Create zip
        run: |
          mkdir -p flora-extension
          cp manifest.json flora-extension/
          cp -r dist flora-extension/
          zip -r flora-extension.zip flora-extension

      # see customization options at:
      # https://github.com/marketplace/actions/gh-release#-customizing
      - name: Draft release
        if: github.ref_type != 'tag' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v3
        with:
          tag_name: draft
          files: flora-extension.zip
          draft: true
      - name: Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v3
        with:
          files: flora-extension.zip
          make_latest: true
